// Code generated by go-swagger; DO NOT EDIT.

// Package restapi CutomLogs
//
//
//
//
//  Schemes:
//    http
//  Host: localhost:8090
//  BasePath: /utility/log/v1
//  Version: 0.1.0_inProgress
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
