// Code generated by go-swagger; DO NOT EDIT.

package log_preserve

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	"customlogs/models"
)

// GetPreserveOKCode is the HTTP code returned for type GetPreserveOK
const GetPreserveOKCode int = 200

/*GetPreserveOK Ok

swagger:response getPreserveOK
*/
type GetPreserveOK struct {
	/*No of actual records against the filter applied. Since it is NRT API so a little discrepancy could be expected

	 */
	XExpectedRecordsCount int64 `json:"X-Expected-Records-Count"`
	/*No of records returned against the API request

	 */
	XFetchedRecordsCount int64 `json:"X-Fetched-Records-Count"`

	/*
	  In: Body
	*/
	Payload models.Response `json:"body,omitempty"`
}

// NewGetPreserveOK creates GetPreserveOK with default headers values
func NewGetPreserveOK() *GetPreserveOK {

	return &GetPreserveOK{}
}

// WithXExpectedRecordsCount adds the xExpectedRecordsCount to the get preserve o k response
func (o *GetPreserveOK) WithXExpectedRecordsCount(xExpectedRecordsCount int64) *GetPreserveOK {
	o.XExpectedRecordsCount = xExpectedRecordsCount
	return o
}

// SetXExpectedRecordsCount sets the xExpectedRecordsCount to the get preserve o k response
func (o *GetPreserveOK) SetXExpectedRecordsCount(xExpectedRecordsCount int64) {
	o.XExpectedRecordsCount = xExpectedRecordsCount
}

// WithXFetchedRecordsCount adds the xFetchedRecordsCount to the get preserve o k response
func (o *GetPreserveOK) WithXFetchedRecordsCount(xFetchedRecordsCount int64) *GetPreserveOK {
	o.XFetchedRecordsCount = xFetchedRecordsCount
	return o
}

// SetXFetchedRecordsCount sets the xFetchedRecordsCount to the get preserve o k response
func (o *GetPreserveOK) SetXFetchedRecordsCount(xFetchedRecordsCount int64) {
	o.XFetchedRecordsCount = xFetchedRecordsCount
}

// WithPayload adds the payload to the get preserve o k response
func (o *GetPreserveOK) WithPayload(payload models.Response) *GetPreserveOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get preserve o k response
func (o *GetPreserveOK) SetPayload(payload models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPreserveOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header X-Expected-Records-Count

	xExpectedRecordsCount := swag.FormatInt64(o.XExpectedRecordsCount)
	if xExpectedRecordsCount != "" {
		rw.Header().Set("X-Expected-Records-Count", xExpectedRecordsCount)
	}

	// response header X-Fetched-Records-Count

	xFetchedRecordsCount := swag.FormatInt64(o.XFetchedRecordsCount)
	if xFetchedRecordsCount != "" {
		rw.Header().Set("X-Fetched-Records-Count", xFetchedRecordsCount)
	}

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.Response{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetPreserveUnauthorizedCode is the HTTP code returned for type GetPreserveUnauthorized
const GetPreserveUnauthorizedCode int = 401

/*GetPreserveUnauthorized Unauthorized



swagger:response getPreserveUnauthorized
*/
type GetPreserveUnauthorized struct {

	/*
	  In: Body
	*/
	Payload models.Error `json:"body,omitempty"`
}

// NewGetPreserveUnauthorized creates GetPreserveUnauthorized with default headers values
func NewGetPreserveUnauthorized() *GetPreserveUnauthorized {

	return &GetPreserveUnauthorized{}
}

// WithPayload adds the payload to the get preserve unauthorized response
func (o *GetPreserveUnauthorized) WithPayload(payload models.Error) *GetPreserveUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get preserve unauthorized response
func (o *GetPreserveUnauthorized) SetPayload(payload models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPreserveUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetPreserveForbiddenCode is the HTTP code returned for type GetPreserveForbidden
const GetPreserveForbiddenCode int = 403

/*GetPreserveForbidden Forbidden



swagger:response getPreserveForbidden
*/
type GetPreserveForbidden struct {

	/*
	  In: Body
	*/
	Payload models.Error `json:"body,omitempty"`
}

// NewGetPreserveForbidden creates GetPreserveForbidden with default headers values
func NewGetPreserveForbidden() *GetPreserveForbidden {

	return &GetPreserveForbidden{}
}

// WithPayload adds the payload to the get preserve forbidden response
func (o *GetPreserveForbidden) WithPayload(payload models.Error) *GetPreserveForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get preserve forbidden response
func (o *GetPreserveForbidden) SetPayload(payload models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPreserveForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetPreserveMethodNotAllowedCode is the HTTP code returned for type GetPreserveMethodNotAllowed
const GetPreserveMethodNotAllowedCode int = 405

/*GetPreserveMethodNotAllowed Method Not Allowed



swagger:response getPreserveMethodNotAllowed
*/
type GetPreserveMethodNotAllowed struct {

	/*
	  In: Body
	*/
	Payload models.Error `json:"body,omitempty"`
}

// NewGetPreserveMethodNotAllowed creates GetPreserveMethodNotAllowed with default headers values
func NewGetPreserveMethodNotAllowed() *GetPreserveMethodNotAllowed {

	return &GetPreserveMethodNotAllowed{}
}

// WithPayload adds the payload to the get preserve method not allowed response
func (o *GetPreserveMethodNotAllowed) WithPayload(payload models.Error) *GetPreserveMethodNotAllowed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get preserve method not allowed response
func (o *GetPreserveMethodNotAllowed) SetPayload(payload models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPreserveMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetPreserveInternalServerErrorCode is the HTTP code returned for type GetPreserveInternalServerError
const GetPreserveInternalServerErrorCode int = 500

/*GetPreserveInternalServerError Internal Server Error



swagger:response getPreserveInternalServerError
*/
type GetPreserveInternalServerError struct {

	/*
	  In: Body
	*/
	Payload models.Error `json:"body,omitempty"`
}

// NewGetPreserveInternalServerError creates GetPreserveInternalServerError with default headers values
func NewGetPreserveInternalServerError() *GetPreserveInternalServerError {

	return &GetPreserveInternalServerError{}
}

// WithPayload adds the payload to the get preserve internal server error response
func (o *GetPreserveInternalServerError) WithPayload(payload models.Error) *GetPreserveInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get preserve internal server error response
func (o *GetPreserveInternalServerError) SetPayload(payload models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPreserveInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
